### ISSUE TITLE
create documentation

### ISSUE THREAD

**Issue by kvackkvack** [kvackkvack/cratch#1]
before creating further commands, I should document what's already here more thoroughly. mainly for use when I decide to make a scratch post about this. also because that's what reasonable people do.

**Comment by liam4** [comment]
I was going to say [hardly](https://github.com/liam4/rpg-base/commit/ac825a28490399ae0607e8221715a947d1a00e66) but I'm not a reasonable person

**Comment by kvackkvack** [comment]
Oops, seems I forgot about this. Will have to do tomorrow instead.
> I was going to say [hardly](https://github.com/liam4/rpg-base/commit/ac825a28490399ae0607e8221715a947d1a00e66) but I'm not a reasonable person  

Hey, at least you took the time to write that commit description. :P

**Comment by kvackkvack** [comment]
Just finished wiki documentation!
